"""Prepare a morphology-stratified attention-loss ablation dataset.

Parents are selected from every sufficiently mature individual in an existing
MACD run.  Children are generated by chaining MACD's original mutation
operator until a requested Hamming-distance stratum is reached.
"""

import argparse
import csv
import json
import os
import random
import re
import shutil
import sys

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if PROJECT_ROOT not in sys.path:
    sys.path.insert(0, PROJECT_ROOT)

import numpy as np
from evogym import get_full_connectivity, has_actuator, hashable, is_connected

import tests.run_offspring_attention_ablation as roaa
from macd.controller_distillation import same_voxel_mask, should_skip_warmup
from utils.algo_utils import mutate

ROOT_DIR = PROJECT_ROOT

GEN_RE = re.compile(r"Running generation (\d+)")
SURV_RE = re.compile(r"survivor IDs\(\d+\):\[([^\]]+)\]")
ROW_RE = re.compile(r"^\s*(\d+)\s+(\d+)\s+(-?\d+\.\d+)\s*$")
DEFAULT_DISTANCE_BINS = ((1, 5), (6, 10), (11, 15), (16, 20))


def parse_distance_bin(value):
    match = re.fullmatch(r"(\d+)-(\d+)", value)
    if match is None:
        raise argparse.ArgumentTypeError(
            "distance bins must use LOW-HIGH syntax, for example 1-5"
        )
    low, high = int(match.group(1)), int(match.group(2))
    if low <= 0 or high < low:
        raise argparse.ArgumentTypeError("distance bins require 0 < LOW <= HIGH")
    return low, high


def parse_args():
    parser = argparse.ArgumentParser(
        description="Prepare stratified offspring for the loss ablation."
    )
    parser.add_argument(
        "--result-dir",
        default=os.path.join(ROOT_DIR, "result", "MACD(2loss)", "Walker-v0", "0"),
        help="Existing MACD run containing out.txt, structures/ and controllers/.",
    )
    parser.add_argument(
        "--output-dir",
        default=os.path.join(
            ROOT_DIR, "result", "attention_loss_ablation_stratified_20"
        ),
        help="Output folder receiving parents/ and offspring/.",
    )
    parser.add_argument("--env", default="Walker-v0")
    parser.add_argument("--min-parent-maturity", type=int, default=13)
    parser.add_argument("--parent-pool-size", type=int, default=30)
    parser.add_argument(
        "--distance-bins",
        type=parse_distance_bin,
        nargs="+",
        default=list(DEFAULT_DISTANCE_BINS),
    )
    parser.add_argument("--offspring-per-bin", type=int, default=5)
    parser.add_argument("--sampling-seed", type=int, default=20260818)
    parser.add_argument("--mutation-seed-base", type=int, default=1000)
    parser.add_argument("--max-chain-steps", type=int, default=30)
    parser.add_argument("--max-mutation-retries", type=int, default=100)
    parser.add_argument(
        "--regenerate",
        action="store_true",
        help="Replace previously prepared parents and offspring in output-dir.",
    )
    return parser.parse_args()


def validate_args(args):
    if args.min_parent_maturity < 1:
        raise ValueError("--min-parent-maturity must be positive")
    if args.parent_pool_size <= 0:
        raise ValueError("--parent-pool-size must be positive")
    if args.offspring_per_bin <= 0:
        raise ValueError("--offspring-per-bin must be positive")
    if args.max_chain_steps <= 0 or args.max_mutation_retries <= 0:
        raise ValueError("mutation limits must be positive")
    bins = sorted(args.distance_bins)
    if bins != list(args.distance_bins):
        raise ValueError("--distance-bins must be ordered by increasing distance")
    for previous, current in zip(bins, bins[1:]):
        if current[0] <= previous[1]:
            raise ValueError("--distance-bins must not overlap")


def parse_last_completed_generation(out_path):
    """Return the last generation block that recorded a promotion."""
    with open(out_path, encoding="utf-8", errors="replace") as output_file:
        lines = output_file.readlines()
    blocks = []
    starts = [i for i, line in enumerate(lines) if GEN_RE.search(line)]
    for index, start in enumerate(starts):
        end = starts[index + 1] if index + 1 < len(starts) else len(lines)
        block = lines[start:end]
        match = next(
            (SURV_RE.search(line) for line in block if SURV_RE.search(line)), None
        )
        if match is None:
            continue
        blocks.append(
            {
                "generation": int(GEN_RE.search(lines[start]).group(1)),
                "survivor_ids": [int(value) for value in match.group(1).split(",")],
            }
        )
    if not blocks:
        raise RuntimeError("No completed generation block found in " + out_path)
    return blocks[-1]


def parse_all_individuals(out_path):
    """Return each individual's last printed maturity and fitness."""
    individuals = {}
    with open(out_path, encoding="utf-8", errors="replace") as output_file:
        for line in output_file:
            match = ROW_RE.match(line)
            if match is None:
                continue
            individual_id = int(match.group(1))
            individuals[individual_id] = {
                "id": individual_id,
                "maturity": int(match.group(2)),
                "fitness": float(match.group(3)),
            }
    if not individuals:
        raise RuntimeError("No individual fitness rows found in " + out_path)
    return individuals


def eligible_parent_records(result_dir, individuals, min_maturity):
    records = []
    for individual_id, record in individuals.items():
        if record["maturity"] < min_maturity:
            continue
        structure_path = os.path.join(
            result_dir, "structures", "{}.npz".format(individual_id)
        )
        controller_path = os.path.join(
            result_dir, "controllers", "{}.pt".format(individual_id)
        )
        if not os.path.isfile(structure_path) or not os.path.isfile(controller_path):
            continue
        item = dict(record)
        item["structure_path"] = structure_path
        item["controller_path"] = controller_path
        records.append(item)
    return records


def body_hamming_distance(first, second):
    return int(np.sum(np.asarray(first) != np.asarray(second)))


def select_diverse_parents(records, bodies, pool_size):
    """Deterministic farthest-point selection with fitness and ID tie-breaks."""
    if len(records) < pool_size:
        raise RuntimeError(
            "Only {} eligible parents, fewer than requested pool size {}".format(
                len(records), pool_size
            )
        )
    by_id = {record["id"]: record for record in records}
    first_id = min(records, key=lambda item: (-item["fitness"], item["id"]))["id"]
    selected = [first_id]
    selection_distances = {first_id: None}
    remaining = set(by_id) - {first_id}
    while len(selected) < pool_size:
        scored = []
        for candidate_id in remaining:
            minimum_distance = min(
                body_hamming_distance(bodies[candidate_id], bodies[selected_id])
                for selected_id in selected
            )
            scored.append(
                (
                    -minimum_distance,
                    -by_id[candidate_id]["fitness"],
                    candidate_id,
                    minimum_distance,
                )
            )
        _, _, next_id, minimum_distance = min(scored)
        selected.append(next_id)
        selection_distances[next_id] = minimum_distance
        remaining.remove(next_id)
    return selected, selection_distances


def most_similar_parents(child_body, parent_ids, bodies):
    """Return the first best parent, score, and all ties in pool order."""
    counts = [
        int(np.sum(same_voxel_mask(bodies[parent_id], child_body)))
        for parent_id in parent_ids
    ]
    best_count = max(counts)
    tied_ids = [
        parent_id
        for parent_id, count in zip(parent_ids, counts)
        if count == best_count
    ]
    return tied_ids[0], best_count, tied_ids


def most_similar_parent(child_body, parent_ids, bodies):
    """Backward-compatible two-value parent selection helper."""
    parent_id, count, _ = most_similar_parents(child_body, parent_ids, bodies)
    return parent_id, count


def generate_stratified_child(
    parent_ids,
    bodies,
    distance_bin,
    bin_index,
    child_slot,
    sampling_seed,
    mutation_seed_base,
    record,
    selected_hashes,
    max_chain_steps,
    max_restarts,
):
    low, high = distance_bin
    parent_order = list(parent_ids)
    random.Random(sampling_seed + bin_index * 1009 + child_slot).shuffle(parent_order)
    last_trajectory = []
    for restart in range(max_restarts):
        direct_parent_id = parent_order[restart % len(parent_order)]
        direct_parent = bodies[direct_parent_id]
        mutation_seed = (
            mutation_seed_base
            + bin_index * 100000
            + child_slot * max_restarts
            + restart
        )
        roaa.set_all_seeds(mutation_seed)
        current = np.asarray(direct_parent).copy()
        trajectory = []
        for chain_step in range(1, max_chain_steps + 1):
            child = mutate(current, record)
            if child is None:
                break
            current = np.asarray(child).copy()
            distance = body_hamming_distance(direct_parent, current)
            trajectory.append(distance)
            if distance > high:
                break
            if distance < low:
                continue
            child_hash = hashable(current)
            nearest_id, similarity_count, tied_ids = most_similar_parents(
                current, parent_ids, bodies
            )
            if child_hash in selected_hashes or similarity_count < 4:
                break
            if not is_connected(current) or not has_actuator(current):
                break
            selected_hashes.add(child_hash)
            return {
                "child_body": current,
                "direct_parent_id": direct_parent_id,
                "most_similar_parent_id": nearest_id,
                "most_similar_parent_ids": tied_ids,
                "similarity_count": similarity_count,
                "mutation_seed": mutation_seed,
                "mutation_restart": restart + 1,
                "mutation_chain_length": chain_step,
                "distance_trajectory": trajectory,
            }
        last_trajectory = trajectory
    raise RuntimeError(
        "No valid child for distance bin {}-{} slot {} after {} restarts; "
        "last trajectory was {}".format(
            low, high, child_slot, max_restarts, last_trajectory
        )
    )


def clear_generated_directories(output_dir):
    for name in ("parents", "offspring"):
        path = os.path.join(output_dir, name)
        if os.path.isdir(path):
            shutil.rmtree(path)


def print_summary(metadata):
    print(
        "=== Parent pool: {} selected from {} eligible ===".format(
            len(metadata["parents"]), metadata["eligible_parent_count"]
        )
    )
    print("  IDs: {}".format(metadata["selected_parent_ids"]))
    print("=== Offspring distance strata ===")
    counts = {}
    for offspring in metadata["offspring"]:
        label = offspring["distance_bin"]
        counts[label] = counts.get(label, 0) + 1
        print(
            "  offspring_{offspring_index}: bin {distance_bin}, distance "
            "{changed_voxel_count}, direct {direct_parent_id} -> nearest "
            "{most_similar_parent_id} (shared {similarity_count})".format(**offspring)
        )
    print("  Counts: {}".format(counts))


def main():
    args = parse_args()
    validate_args(args)
    os.makedirs(args.output_dir, exist_ok=True)
    metadata_path = os.path.join(args.output_dir, "metadata.json")
    if os.path.exists(metadata_path) and not args.regenerate:
        print("Reusing existing experiment metadata: " + metadata_path)
        with open(metadata_path) as metadata_file:
            print_summary(json.load(metadata_file))
        return
    if args.regenerate:
        clear_generated_directories(args.output_dir)

    out_path = os.path.join(args.result_dir, "out.txt")
    generation = parse_last_completed_generation(out_path)["generation"]
    individuals = parse_all_individuals(out_path)
    eligible = eligible_parent_records(
        args.result_dir, individuals, args.min_parent_maturity
    )
    eligible_bodies = {
        item["id"]: roaa.load_parent_structure(item["structure_path"])
        for item in eligible
    }
    parent_ids, selection_distances = select_diverse_parents(
        eligible, eligible_bodies, args.parent_pool_size
    )
    selected_records = {item["id"]: item for item in eligible if item["id"] in parent_ids}
    bodies = {parent_id: eligible_bodies[parent_id] for parent_id in parent_ids}

    parents_dir = os.path.join(args.output_dir, "parents")
    offspring_dir = os.path.join(args.output_dir, "offspring")
    os.makedirs(parents_dir, exist_ok=True)
    os.makedirs(offspring_dir, exist_ok=True)
    for parent_id in parent_ids:
        shutil.copy2(
            selected_records[parent_id]["structure_path"],
            os.path.join(parents_dir, "{}.npz".format(parent_id)),
        )
        shutil.copy2(
            selected_records[parent_id]["controller_path"],
            os.path.join(parents_dir, "{}.pt".format(parent_id)),
        )
    with open(os.path.join(args.output_dir, "parents.csv"), "w", newline="") as csv_file:
        writer = csv.DictWriter(
            csv_file,
            fieldnames=("selection_order", "id", "maturity", "fitness", "selection_min_distance"),
        )
        writer.writeheader()
        for order, parent_id in enumerate(parent_ids):
            record_item = selected_records[parent_id]
            writer.writerow(
                {
                    "selection_order": order,
                    "id": parent_id,
                    "maturity": record_item["maturity"],
                    "fitness": record_item["fitness"],
                    "selection_min_distance": selection_distances[parent_id],
                }
            )

    mutation_record = {hashable(body): [] for body in eligible_bodies.values()}
    selected_hashes = set(mutation_record)
    offspring_metadata = []
    offspring_index = 0
    for bin_index, distance_bin in enumerate(args.distance_bins):
        low, high = distance_bin
        for child_slot in range(args.offspring_per_bin):
            generated = generate_stratified_child(
                parent_ids,
                bodies,
                distance_bin,
                bin_index,
                child_slot,
                args.sampling_seed,
                args.mutation_seed_base,
                mutation_record,
                selected_hashes,
                args.max_chain_steps,
                args.max_mutation_retries,
            )
            child_body = generated.pop("child_body")
            direct_parent_id = generated["direct_parent_id"]
            nearest_id = generated["most_similar_parent_id"]
            morph = roaa.morphology_metadata(
                bodies[direct_parent_id], child_body, generated["mutation_restart"]
            )
            child_dir = os.path.join(
                offspring_dir, "offspring_{}".format(offspring_index)
            )
            os.makedirs(child_dir, exist_ok=True)
            child_body_path = os.path.join(child_dir, "body.npz")
            parent_body_path = os.path.join(child_dir, "parent_body.npz")
            parent_controller_path = os.path.join(child_dir, "parent_controller.pt")
            np.savez(
                child_body_path, child_body, get_full_connectivity(child_body)
            )
            np.savez(
                parent_body_path,
                bodies[nearest_id],
                get_full_connectivity(bodies[nearest_id]),
            )
            shutil.copy2(
                os.path.join(parents_dir, "{}.pt".format(nearest_id)),
                parent_controller_path,
            )
            child_nonempty = int(np.sum(child_body != 0))
            parent_nonempty = int(np.sum(bodies[nearest_id] != 0))
            metadata = {
                "offspring_index": offspring_index,
                "distance_bin": "{}-{}".format(low, high),
                "distance_bin_low": low,
                "distance_bin_high": high,
                "direct_parent_id": direct_parent_id,
                "most_similar_parent_id": nearest_id,
                "most_similar_parent_ids": generated["most_similar_parent_ids"],
                "similarity_count": generated["similarity_count"],
                "similarity_coverage_child": generated["similarity_count"] / child_nonempty,
                "similarity_coverage_parent": generated["similarity_count"] / parent_nonempty,
                "shared_nonempty_voxel_count": morph["shared_nonempty_voxel_count"],
                "mutation_seed": generated["mutation_seed"],
                "mutation_attempt": generated["mutation_restart"],
                "mutation_restart": generated["mutation_restart"],
                "mutation_chain_length": generated["mutation_chain_length"],
                "distance_trajectory": generated["distance_trajectory"],
                "changed_voxel_count": morph["changed_voxel_count"],
                "changed_voxels": morph["changed_voxels"],
                "direct_parent_body": morph["parent_body"],
                "parent_body": morph["parent_body"],
                "child_body": morph["child_body"],
                "parent_body_hash": hashable(bodies[nearest_id]),
                "child_body_hash": hashable(child_body),
                "parent_body_path": "parent_body.npz",
                "parent_controller_path": "parent_controller.pt",
                "child_body_path": "body.npz",
            }
            if not low <= metadata["changed_voxel_count"] <= high:
                raise AssertionError("generated child is outside its distance bin")
            with open(os.path.join(child_dir, "metadata.json"), "w") as metadata_file:
                json.dump(metadata, metadata_file, indent=2)
            offspring_metadata.append(metadata)
            offspring_index += 1

    expected_total = len(args.distance_bins) * args.offspring_per_bin
    if len(offspring_metadata) != expected_total:
        raise AssertionError(
            "Prepared {} offspring; expected {}".format(
                len(offspring_metadata), expected_total
            )
        )
    bin_counts = {
        "{}-{}".format(low, high): sum(
            child["distance_bin"] == "{}-{}".format(low, high)
            for child in offspring_metadata
        )
        for low, high in args.distance_bins
    }
    if any(count != args.offspring_per_bin for count in bin_counts.values()):
        raise AssertionError("Offspring distance strata are incomplete: {}".format(bin_counts))

    eligible_summary = [
        {
            "id": item["id"],
            "maturity": item["maturity"],
            "fitness": item["fitness"],
        }
        for item in sorted(eligible, key=lambda item: item["id"])
    ]
    top_metadata = {
        "result_dir": os.path.abspath(args.result_dir),
        "env": args.env,
        "generation": generation,
        "min_parent_maturity": args.min_parent_maturity,
        "eligible_parent_count": len(eligible),
        "eligible_parents": eligible_summary,
        "parent_pool_size": args.parent_pool_size,
        "parent_selection": "categorical_hamming_farthest_point",
        "selected_parent_ids": parent_ids,
        "sampling_seed": args.sampling_seed,
        "mutation_seed_base": args.mutation_seed_base,
        "max_chain_steps": args.max_chain_steps,
        "max_mutation_retries": args.max_mutation_retries,
        "distance_bins": [list(value) for value in args.distance_bins],
        "offspring_per_bin": args.offspring_per_bin,
        "offspring_dir": "offspring",
        "parents": [
            {
                "id": parent_id,
                "maturity": selected_records[parent_id]["maturity"],
                "fitness": selected_records[parent_id]["fitness"],
                "selection_order": order,
                "selection_min_distance": selection_distances[parent_id],
                "structure_path": os.path.join(
                    "parents", "{}.npz".format(parent_id)
                ),
                "controller_path": os.path.join(
                    "parents", "{}.pt".format(parent_id)
                ),
            }
            for order, parent_id in enumerate(parent_ids)
        ],
        "offspring": offspring_metadata,
        "distance_bin_counts": bin_counts,
    }
    with open(metadata_path, "w") as metadata_file:
        json.dump(top_metadata, metadata_file, indent=2)
    print_summary(top_metadata)
    print("Experiment prepared under " + os.path.abspath(args.output_dir))


if __name__ == "__main__":
    main()
